name = "ivyar-autopilot-v8"
main = "dist/index.js"
compatibility_date = "2024-01-01"
workers_dev = true
account_id = "c3fa127f606395f347477a3c96fa27cb"

[[kv_namespaces]]
binding = "AUTOPILOT_CACHE"
id = "b538f4fd0eee4ae88fdd3bfe917a08b1"
preview_id = "bdc6f94cf030450e929979dcd2bb800e"

[vars]
ENVIRONMENT = "production"

compatibility_flags = ["nodejs_compat"]

[dev]
port = 8787
local_protocol = "http"
